# Gradle Configuration -- DO NOT TOUCH THESE VALUES.
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx2G

loom_version=1.14-SNAPSHOT
loader_version=0.18.4
fabric_api_version=[VERSIONED]

mod.name=EvergreenHUD
mod.id=evergreenhud
mod.version=3.0.0-alpha.1
mod.group=org.polyfrost